describe('Automating e-commerce site with registration and product ordering.', () => {
  const email = 'r.parves+'+Date.now()+'@gmail.com'
  beforeEach(() => {
    cy.visit('https://automationexercise.com')
  })

  it('Creating account and purchasing a product', () => {
    cy.get('.add-to-cart').should('be.visible')
    cy.get('.add-to-cart').first().click()
    cy.get('#cartModal').should('exist')
    cy.get('#cartModal .modal-title').invoke('text').should('eq', 'Added!')
    cy.get('#cartModal .modal-body a').should('exist')
    cy.get('#cartModal .modal-body a').click()
    cy.get('.breadcrumbs .active').should('exist')
    cy.get('.breadcrumbs .active').invoke('text').should('eq','Shopping Cart')
    cy.get('#do_action a').should('exist')
    cy.get('#do_action a').first().click()
    cy.get('#checkoutModal').should('exist')
    cy.get('#checkoutModal a').click()
    cy.get('[data-qa="signup-name"]').should('exist').type('Rubel Parves')
    cy.get('[data-qa="signup-email"]').should('exist').type(email)
    cy.get('[data-qa="signup-button"]').should('exist').click()
    cy.get('[data-qa="title"] input').first().check()
    cy.get('[data-qa="password"]').should('exist').type('abc12345')
    cy.get('[data-qa="days"]').select('1')
    cy.get('[data-qa="months"]').select('1')
    cy.get('[data-qa="years"]').select('2000')
    cy.get('#newsletter').first().check()
    cy.get('[data-qa="first_name"]').should('exist').type('rubel')
    cy.get('[data-qa="last_name"]').should('exist').type('parves')
    cy.get('[data-qa="company"]').should('exist').type('company')
    cy.get('[data-qa="address"]').should('exist').type('Tejgaon')
    cy.get('[data-qa="address2"]').should('exist').type('Dhaka')
    cy.get('[data-qa="country"]').select('India')
    cy.get('[data-qa="state"]').should('exist').type('Mumbai')
    cy.get('[data-qa="city"]').should('exist').type('pune')
    cy.get('[data-qa="zipcode"]').should('exist').type('110001')
    cy.get('[data-qa="mobile_number"]').should('exist').type('+910123456')
    cy.get('[data-qa="create-account"]').should('exist').click()
    cy.get('[data-qa="continue-button"]').should('exist').click()
    cy.get('.fa-user').should('exist')
    cy.get('.fa-user+b').invoke('text').should('eq','Rubel Parves')
    cy.get('.shop-menu .nav li:nth-child(3) a').should('exist')
    cy.get('.shop-menu .nav li:nth-child(3) a').should('exist').click()
    cy.get('#do_action a').should('exist')
    cy.get('#do_action a').first().click()
    cy.get('[data-qa="checkout-info"]').should('exist')
    cy.get('[data-qa="checkout-info"] #address_delivery .address_firstname.address_lastname').invoke('text').should('eq','Mr. rubel parves')
    cy.get('[data-qa="checkout-info"] #address_invoice .address_firstname.address_lastname').invoke('text').should('eq','Mr. rubel parves')
    cy.get('[data-qa="checkout-info"] #address_delivery li:nth-child(3)').invoke('text').should('eq','company')
    cy.get('[data-qa="checkout-info"] #address_delivery li:nth-child(4)').invoke('text').should('eq','Tejgaon')
    cy.get('[data-qa="checkout-info"] #address_delivery li:nth-child(5)').invoke('text').should('eq','Dhaka')
    cy.get('#product-1').should('exist')
    cy.get('#ordermsg .form-control').should('exist')
    cy.get('#ordermsg .form-control').type('Test Order')
    cy.get('.btn.check_out').should('exist')
    cy.get('.btn.check_out').should('exist').first().click()
    cy.get('[data-qa="name-on-card"]').should('exist').type('Rubel Parves')
    cy.get('[data-qa="card-number"]').should('exist').type('4444 3333 2222 1111')
    cy.get('[data-qa="cvc"]').should('exist').type('444')
    cy.get('[data-qa="expiry-month"]').should('exist').type('11')
    cy.get('[data-qa="expiry-year"]').should('exist').type('2028')
    cy.get('#payment-form').then(form$ => {
      form$.on('submit', e => {
        e.preventDefault();
      })
    })
    cy.get('[data-qa="pay-button"]').should('exist').click()
    cy.get('#success_message .alert-success.alert').invoke('text').then((text) => text.trim()).should('eq','Your order has been placed successfully!')
  })
})